### ISSUE TITLE
Automatisation de la pipeline de déploiement pour l'app-snpay

### ISSUE THREAD

**Issue by zlorgoncho1** [DSsenegal/app-snpay#13]

**Comment by zlorgoncho1** [comment]
Hello @dofbi  , merci de me passer l'accès admin pour ajouter le token vercel au niveau du repository app-snpay, pour que j'automatise le déploiement pour cet application.

**Comment by zlorgoncho1** [comment]
- [ ] Trouver une solution pour faire le fork automatiquement

**Comment by zlorgoncho1** [comment]
Hello @dofbi , voici une proposition pour résoudre le système de mise à jour automatique des branche en l'occurrence, le système de déploiement continu. 

Nous pouvons essayer de configurer des hooks entre deux repositories GitHub. Voici ce que j'ai trouvé durant les recherches:

Étape 1 : Créer un GitHub Action dans le repository A
Créez un fichier `.github/workflows/trigger.yml` dans le repository A.

```yaml
name: Trigger Action in Repo B
on: 
  push:
    branches:
      - main # Déclenchez sur les pushs vers la branche principale
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo A
      uses: actions/checkout@v2
    - name: Trigger workflow in Repo B
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token GitHub pour l'authentification
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token $GITHUB_TOKEN" \      https://api.github.com/repos/OWNER_B/REPO_B/actions/workflows/WORKFLOW_FILE_NAME/dispatches \
          -d '{"ref":"main"}'
```
Le workflow `trigger.yml` se déclenche sur un push vers la branche main.
Il envoie une requête POST à l'API GitHub pour déclencher le workflow `deploy.yml` dans le repository B.

Étape 2 : Configurer le workflow dans le repository B
Créez un fichier `.github/workflows/deploy.yml` dans le repository B.

```yaml
name: Deploy
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo B
      uses: actions/checkout@v2
    - name: Run Deployment Script
      run: |
        # Mettre ici le code de déploiement
```
Le workflow `deploy.yml` est configuré pour se déclencher avec `workflow_dispatch`, qui permet d'être déclenché manuellement ou par une requête API.

Avec cette configuration, un push dans le repository A déclenche automatiquement une action dans le repository B sans besoin d'un serveur intermédiaire. 

Est ce que je peux commencer l'implémentation ?
